const DetailActionTypes = {
  FETCH_DETAIL_START: 'FETCH_DETAIL_START',
  FETCH_DETAIL_SUCCESS: 'FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILURE: 'FETCH_DETAIL_FAILURE'
}

export default DetailActionTypes;