const MasterActionTypes = {
  FETCH_MASTER_START: 'FETCH_MASTER_START',
  FETCH_MASTER_SUCCESS: 'FETCH_MASTER_SUCCESS',
  FETCH_MASTER_FAILURE: 'FETCH_MASTER_FAILURE',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
}

export default MasterActionTypes;
